config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'mandalas#top'

	devise_for :users, :controllers => {
	:registrations => 'users/registrations',
	:sessions => 'users/sessions'
	}

	get 'users/:id/graph' => 'users#graph', as: 'user_graph'
	resources :users, only: [:show, :edit, :update, :destroy]

	resources :mandalas

	get 'tasks/:id/done' => 'tasks#done', as: 'task_done'
	resources :tasks, only: [:create, :destroy]

end

app/models/mandala.rb
class Mandala < ApplicationRecord

	belongs_to :user
	has_many :elements, :dependent => :destroy
	accepts_nested_attributes_for :elements, allow_destroy: true

	validates :target,	presence: true,
						length: { maximum: 20 }

end

app/controllers/mandalas_controller.rb
class MandalasController < ApplicationController

#mandala_complete?メソッドは、ほかのコントローラーと共通の処理のため、Aplication_Helperに記述
before_action :sign_in_auth, only:[:new]
before_action :mandala_complete?, only:[:edit]

  #GET / (root_path)
  def top
      gon.registfail = regist_params[:regist] #会員登録認証失敗時のパラメータ
      gon.log_in_fail = log_in_params[:log_in] #ログイン失敗時のパラメータ
  end

  #GET /mandalas/new (new_mandala_path)
  #params[:step]のvalueで、処理を分岐します。
  #params[:element_edit] trueで、必要な要素を中心とした、行動入力画面へ
  def new
    @main_title = "マンダラチャートを作成しよう！"
    if params[:step] == "2"
      new_step2
    elsif params[:step] == "3"
      new_step3
    elsif params[:element_edit]
      new_activity
    else
      new_step1
    end
  end

  #POST /mandalas (mandalas_path)
  #params[:step]のvalueで、処理を分岐します。
  def create
    if params[:step] == "1" #達成したい目標を保存する
      create_step1
    elsif params[:step] == "2" #目標に紐づく必要な要素を保存
      create_step2
    elsif params[:step] == "3" #チャート作成完了
      create_step3
    else #params[:step] == "4"  必要な行動を保存
      create_activity
    end
  end

  #GET /mandala/:id/edit (edit_mandala_path)
  def edit
    @mandala = Mandala.find_by(user_id: current_user, achieved: false)
    @main_title = "マンダラチャート編集"
    gon.form_edit = true
    if params[:element_edit] #必要な行動編集画面へ
      gon.step ="el_edit"
      @step = "el_edit"
      @mandala_center = Element.find_by(mandala_id: @mandala.id, number: params[:element_edit].to_i)
      @mandala_center.activities.build
      square_text2
      element_activity_text
    else
      @step = "edit"
      gon.step = "edit"
      @mandala_center = Mandala.find_by(user_id: current_user.id, achieved: false)
      @mandala_center.elements.build
      square_text1
      mandala_element_text
    end
  end

  #POST /mandala/:id (mandala_path)
  def update
    if params[:step] == "el_edit" #必要な行動入力画面からPOSTされてきたら
      create_activity
    else
      create_step3
    end
  end

  #DELETE /mandala/:id (mandala_path)
  def destroy
    mandala = Mandala.find(params[:id])
    mandala.destroy
    redirect_to user_path(current_user.id)
  end




  private

#-------------------- Mandalaチャートnewアクション用 --------------------#

  def new_step1
    @step = 1 #view分岐用
    gon.step = 1 #jQuery分岐用
    @mandala_center = Mandala.new
    @mandala_center.elements.build
    @main_text = "STEP1. まずは達成したい目標を中心のマスに入力しましょう！"
    @center_text = "達成したい目標"
  end

  def new_step2
    @step = 2 #view分岐用
    gon.step = 2 #jQuery分岐用
    @mandala_center = Mandala.find_by(user_id: current_user.id, achieved: false)
    @mandala_center.elements.build
    @main_text = "STEP2. 目標を達成するために必要な要素を入力していきましょう！"
    square_text1
    @element_text5 = @mandala_center.target
  end

  def new_step3
    @step = 3 #view分岐用
    gon.step = 3 #jQuery分岐用
    @mandala_center = Mandala.find_by(user_id: current_user.id, achieved: false)
    @main_text = "STEP3. 各要素を選択し、必要な行動を入力していきましょう！"
    square_text1
    mandala_element_text
  end

  def new_activity
    @step = 4 #view分岐用
    gon.step = 4 #jQuery分岐用
    mandala = Mandala.find_by(user_id: current_user, achieved: false)
    @mandala_center = Element.find_by(mandala_id: mandala.id, number: params[:element_edit].to_i)
    @main_text = "要素を実現するために必要な行動を入力していきましょう！"
    square_text2
    if @mandala_center.activities.present? #すでに必要な行動が入力済みなら、テキスト情報をviewへ渡す
      element_activity_text
    end
    @mandala_center.activities.build
    @element_text5 = @mandala_center.target
  end

#-------------------- Mandalaチャートnewアクション用 --------------------#

#---------------- Mandalaチャート作成ページ text埋め込み用 ----------------#

  def square_text1
    @center_text = "達成したい目標"
    @around_text = "必要な要素"
  end

  def square_text2
    @center_text = "必要な要素"
    @around_text = "必要な行動"
  end

  def mandala_element_text #viewで表示するテキスト
    @element_text1 = Element.find_by(mandala_id: @mandala_center.id, number: 1).target
    @element_text2 = Element.find_by(mandala_id: @mandala_center.id, number: 2).target
    @element_text3 = Element.find_by(mandala_id: @mandala_center.id, number: 3).target
    @element_text4 = Element.find_by(mandala_id: @mandala_center.id, number: 4).target
    @element_text5 = @mandala_center.target
    @element_text6 = Element.find_by(mandala_id: @mandala_center.id, number: 5).target
    @element_text7 = Element.find_by(mandala_id: @mandala_center.id, number: 6).target
    @element_text8 = Element.find_by(mandala_id: @mandala_center.id, number: 7).target
    @element_text9 = Element.find_by(mandala_id: @mandala_center.id, number: 8).target
  end

  def element_activity_text #viewで表示するテキスト
    @element_text1 = Activity.find_by(element_id: @mandala_center.id, number: 1).target
    @element_text2 = Activity.find_by(element_id: @mandala_center.id, number: 2).target
    @element_text3 = Activity.find_by(element_id: @mandala_center.id, number: 3).target
    @element_text4 = Activity.find_by(element_id: @mandala_center.id, number: 4).target
    @element_text5 = @mandala_center.target
    @element_text6 = Activity.find_by(element_id: @mandala_center.id, number: 5).target
    @element_text7 = Activity.find_by(element_id: @mandala_center.id, number: 6).target
    @element_text8 = Activity.find_by(element_id: @mandala_center.id, number: 7).target
    @element_text9 = Activity.find_by(element_id: @mandala_center.id, number: 8).target
  end

#---------------- Mandalaチャート作成ページ viewの分岐用 ----------------#

#---------------- Mandalaチャートcreateアクション用 ----------------#

  def create_step1
    mandala = current_user.mandalas.build(mandala_params)
    if mandala.save
      redirect_to new_mandala_path(step: 2)
    else
      redirect_to new_mandala_path
      flash[:errors] = mandala.errors.full_messages
    end
  end

  def create_step2
    mandala = Mandala.find_by(user_id: current_user.id, achieved: false)
    if mandala.update(mandala_params)
      redirect_to new_mandala_path(step: 3)
    else
      redirect_to new_mandala_path(step:2, mandala: mandala_params[:mandala])
      flash[:errors] = mandala.errors.full_messages
    end
  end

  def create_step3
    mandala = Mandala.find_by(user_id: current_user.id, achieved: false)
    unless activity_complete_auth(mandala) #必要な行動が入力されていないものがあるか判定
      flash[:errors] = ["必要な行動が入力されていない要素があります。"]
      redirect_to new_mandala_path(step:3)
    else
      if mandala.update(mandala_params) #例外処理
        redirect_to user_path(current_user.id)
      else
        if request.path.include?(mandala_path(mandala.id))
          redirect_to edit_mandala_path
        else
          redirect_to new_mandala_path(step:3)
          flash[:errors] = mandala.errors.full_messages
        end
      end
    end
  end


  def create_activity
    mandala = Mandala.find_by(user_id: current_user.id, achieved: false)
    element = Element.find_by(mandala_id: mandala.id, number: params[:element][:number].to_i )
    if element.update(element_params)
      if request.path.include?(mandala_path(mandala.id)) #リクエストURLをチェック(mandala/:id/editから来たらtrue)
        redirect_to edit_mandala_path(mandala.id)
      else
        redirect_to new_mandala_path(step: 3)
      end
    else #update失敗時
      if request.path.include?(mandala_path(mandala.id)) #リクエストURLをチェック(mandala/:id/editから来たらtrue)
        redirect_to edit_mandala_path(element_edit: params[:element][:number].to_i)
        flash[:errors] = element.errors.full_messages
      else
        redirect_to new_mandala_path(element_edit: params[:element][:number].to_i)
        flash[:errors] = element.errors.full_messages
      end
    end
  end

#---------------- 各認証チェックアクション ----------------#

  #必要な行動をすべて入力済みかチェック(STEP3用)
  def activity_complete_auth(mandala)
    mandala.elements.each do |element|
      unless element.activities.present?
        return false
      end
    end
    return true
  end

  #ログイン認証用
  def sign_in_auth
    unless user_signed_in?
      redirect_to root_path
    end
  end
#-------------------- 以下ストロングパラメータの定義 --------------------#

  def mandala_params
    params.require(:mandala).permit(:user_id, :target, :achieved,
                    elements_attributes: [:id, :mandala_id, :target, :number, :_destroy])
  end

  def element_params
    params.require(:element).permit(:mandala_id, :target,
                    activities_attributes: [:id, :element_id, :target, :number, :_destroy])
  end

  def regist_params  # ユーザー認証失敗時のパラメーターチェック
    params.permit(:regist)
  end

  def log_in_params  # ユーザー認証失敗時のパラメーターチェック
    params.permit(:log_in)
  end

  def step_params  # マンダラチャート作成STEPのパラメーターチェック
    params.permit(:step)
  end

  def element_edit_params  # マンダラチャート作成Elementのパラメーターチェック
    params.permit(:element_edit)
  end

end

app/helpers/mandalas_helper.rb
module MandalasHelper
end

app/views/mandalas/_element_form.html.erb
	<% if step == 1 || step == 2 %> <!-- マンダラチャート目標 & 必要な要素入力画面用 -->
		<%= f.fields_for :elements do |m| %>
			<%= m.hidden_field :target, class: "element_val" %>
			<%= m.hidden_field :number, :value => value, class: "element_num" %>
		<% end %>
	<% elsif step == 3 %>
		<%= f.fields_for :elements, Element.find_by(mandala_id: mandala_center.id, number: value) do |m| %>
			<%= m.hidden_field :target, class: "element_val" %>
			<%= m.hidden_field :number, :value => value, class: "element_num" %>
		<% end %>
		<% if Element.find_by(mandala_id: mandala_center.id, number: value).activities.present? %>
			<%= hidden_field_tag :activitiy_comp, true %>
		<% end %>
	<% elsif step == "edit" %>
		<%= f.fields_for :elements, Element.find_by(mandala_id: mandala_center.id, number: value) do |m| %>
			<%= m.hidden_field :target, class: "element_val" %>
			<%= m.hidden_field :number, :value => value, class: "element_num" %>
		<% end %>
	<% elsif mandala_center.activities.present? %> <!-- すでに必要な行動を入力しているか確認 -->
		<%= f.fields_for :activities, Activity.find_by(element_id: mandala_center.id, number: value) do |m| %>
			<%= m.hidden_field :target, class: "element_val" %>
			<%= m.hidden_field :number, :value => value, class: "element_num" %>
		<% end %>
	<% else %>
		<%= f.fields_for :activities do |m| %>
			<%= m.hidden_field :target, class: "element_val" %>
			<%= m.hidden_field :number, :value => value, class: "element_num" %>
		<% end %>
	<% end %>

app/views/mandalas/edit.html.erb
<div class="container-main">
	<header class="text-center">
		<h2>チャートを編集</h2>
	</header>
	<div class="container-mandalas text-center">
		<%= form_for @mandala_center, url: mandala_path, method: :patch do |f| %>
		<%= hidden_field_tag :step, @step %>
			<div class="mandalas-row">
				<div class="squares squares-gray">
					<div id="element1" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text1 %></p>
							<%= render 'mandalas/element_form',step: @step, value: 1, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element2" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text2 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 2, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element3" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text3 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 3, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
			</div>
			<div class="mandalas-row">
				<div class="squares squares-gray">
					<div id="element4" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text4 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 4, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-white">
					<div id="element_center" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @center_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text5 %></p>
							<%= f.hidden_field :target, class: "element_val" %>
							<%= f.hidden_field :number %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element5" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text6 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 5, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
			</div>
			<div class="mandalas-row">
				<div class="squares squares-gray">
					<div id="element6" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text7 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 6, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element7" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text8 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 7, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element8" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text9 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 8, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
			</div>
			<div class="row margin-top center-block">
				<div class="col-md-4">
					<% if @step == "el_edit" %>
						<%= link_to "前に戻る", edit_mandala_path(@mandala.id), class: "button button-blue" %>
					<% end %>
				</div>
				<div class="col-md-4">
					<%= f.submit "保存する", class: "button button-blue" %>
				</div>
				<div class="col-md-2 delete_link">
					<a class="delete_mandala modal_open" target="#delete_field">チャートを削除する</a>
				</div>
			</div>
		<% end %>
	</div>
</div>

<!-- 入力フォーム -->
<div id="input-modal" class="container">
	<i id="modal_close" class="fas fa-times pull-right fa-lg"></i>
	<div class="row">
		<div id="modal-header" class="row text-center">
			<h2 id="header-text"></h2>
		</div>
	</div>
	<div class="row cp_iptxt">
		<input id="input" class="" type="text" maxlength='30' placeholder="入力してください">
	</div>
	<div class="row text-center">
		<button id="done" class="button button-blue margin-top">入力OK</button>
	</div>
</div>

<div id="delete_field">
	<i id="modal_close" class="fas fa-times pull-right fa-lg"></i>
	<div class="text-center">
		<p class="h4"><i class="fas fa-exclamation-circle"></i> 一度削除してしまうと元に戻せません。</p>
		<p class="h4">それでもよろしいですか？</p>
	</div>
	<div class="row text-center">
		<%= link_to "削除する", mandala_path(@mandala.id), method: :delete, class: "button button-red margin-top" %>
	</div>
</div>


<%= javascript_include_tag "mandalas_new.js" %>

app/views/mandalas/new.html.erb
<div class="container-main">
	<header class="text-center">
		<h1>マンダラチャートを作成しよう!</h1>
		<p><%= @main_text %></p>
	</header>
	<div class="error_message_area text-center">
		<% if flash[:errors] %>
			<span>エラー発生:</span>
			<% flash[:errors].each do |message| %>
				<span><%= message %></span>
			<% end %>
		<% end %>
	</div>
	<% if @step == 1 %>
		<div class="info_field">
			<p class="info_title"><i class="fas fa-info-circle"></i> Information</p>
			<p class="info_text">
				達成したい目標を入力してくだ<br>
				さい。<br>
				後で編集することもできます。<br>
			</p>
		</div>
	<% elsif @step == 2 %>
		<div class="info_field">
			<p class="info_title"><i class="fas fa-info-circle"></i> Information</p>
			<p class="info_text">
				目標達成に必要な要素を入力してくだ<br>
				さい。<br>
				＜例＞<br>
				目標：英語を話せるようになる<br>
				要素：語彙力、リスニング力 etc...
			</p>
		</div>
	<% elsif @step == 3 %>
		<div class="info_field">
			<p class="info_title"><i class="fas fa-info-circle"></i> Information</p>
			<p class="info_text">
				各要素をクリックすると、<br>
				行動入力画面に遷移します。<br>
				遷移先では要素の編集をすることも<br>
				できます。<br>
			</p>
		</div>
	<% elsif @step == 4 %>
		<div class="info_field">
			<p class="info_title"><i class="fas fa-info-circle"></i> Information</p>
			<p class="info_text">
				要素を実現するために必要な行動を<br>
				入力してください。<br>
				すべての行動を入力する必要は<br>
				ありません。<br>
				(後から編集することが出来ます。)
			</p>
		</div>
	<% end %>
	<div class="container-mandalas text-center">
		<%= form_for @mandala_center, url: mandalas_path, method: :post do |f| %>
		<%= hidden_field_tag :step, @step %>
			<div class="mandalas-row">
				<div class="squares squares-gray">
					<div id="element1" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text1 %></p>
							<%= render 'mandalas/element_form',step: @step, value: 1, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element2" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text2 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 2, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element3" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text3 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 3, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
			</div>
			<div class="mandalas-row">
				<div class="squares squares-gray">
					<div id="element4" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text4 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 4, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-white">
					<div id="element_center" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @center_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text5 %></p>
							<%= f.hidden_field :target, class: "element_val" %>
							<%= f.hidden_field :number %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element5" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text6 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 5, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
			</div>
			<div class="mandalas-row">
				<div class="squares squares-gray">
					<div id="element6" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text7 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 6, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element7" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text8 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 7, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
				<div class="squares squares-gray">
					<div id="element8" class="box modal_open" target="#input-modal">
						<div class="box-header">
							<p class="element_title"><%= @around_text %></p>
						</div>
						<div class="box-body">
							<p class="text"><%= @element_text9 %></p>
							<%= render 'mandalas/element_form', step: @step, value: 8, f:f, mandala_center: @mandala_center %>
						</div>
					</div>
				</div>
			</div>
			<div class="margin-top row">
				<div class="col-md-4">
					<% if @step == 4 %>
						<%= link_to "前に戻る", new_mandala_path(step: 3), class: "button button-white" %>
					<% end %>
				</div>
				<div class="col-md-4">
					<% if @step == 3 %>
						<%= f.submit "完成！", class: "button button-blue" %>
					<% else %>
						<%= f.submit "保存して次へ", class: "button button-blue" %>
					<% end %>
				</div>
			</div>
	<% end %>
	</div>
</div>

<!-- 入力フォーム -->
<div id="input-modal" class="container">
	<i id="modal_close" class="fas fa-times pull-right fa-lg"></i>
	<div class="row">
		<div id="modal-header" class="row text-center">
			<h2 id="header-text"></h2>
		</div>
	</div>
	<div class="row cp_iptxt">
		<input id="input" class="" type="text" maxlength='20' placeholder="入力してください(20文字以内)">
	</div>
	<div class="row text-center">
		<button id="done" class="button button-blue margin-top">入力OK</button>
	</div>
</div>


<%= javascript_include_tag "mandalas_new.js" %>

app/views/mandalas/top.html.erb
<div class="scroll-field">

	<div class="area content-1 text-center">
		<div class ="content-text">
			<h1>Manda-la</h1>
			<p>あなたの人生がより楽しく、より豊かなものに。</p>
		</div>
	</div>
	<div class="area content-2 text-center">
		<div class ="content-text-2">
			<h2>About</h2>
			<p>
				「Manda-la」は、あなたの目標達成を支援するサイトです。<br>
				マンダラチャートを使用し、目標を達成するために必要な要素を洗い出すことで、<br>
				自分に必要なことは何なのだろう？という思考の整理をお手伝いします。
			</p>
		</div>
		<div class ="content-text-2">
			<h2>マンダラチャートとは？</h2>
			<p>
				マンダラチャートは、3×3の9マスの枠で構成される フレームワークです。<br>
				非常にシンプルな フレームワークですが、シンプルゆえに応用の幅も広く、<br>
				事業計画やアイデア出し、勉強、スケジュール作成などあらゆるシーンに応用できます。
			</p>
		</div>
	</div>
	<div class="area content-3">
		<section class="content-text">
			<p class="text-center h1">さあ、あなたも始めてみましょう！</p>
			<p class="text-center h1">まずはログインから</p>
			<div class="content-btn">
				<a class="button button-blue margin-right modal_open" target="#modal1">会員登録</a>
				<a class="button button-blue modal_open" target="#modal2">ログイン</a>
			</div>
		</section>
	</div>
</div>

<!---- モーダルウィンドウ ---->
<div id="modal1" class="modal-container">
	<i id="modal_close" class="fas fa-times pull-right fa-lg"></i>

	<h2 class="text-center">会員登録</h2>

	<div class="text-center">

	<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

		<%if flash[:message] %>
			<% flash[:message].each do |message| %>
				<p class="text-danger"><%= message %></p>
			<% end %>
		<% end %>

		<div class="field cp_iptxt">
			<%= f.text_field :name, placeholder: "名前(10文字以内)", autofocus: true, autocomplete: "name", class: "name", :size => "" %>
			<i class="fa fa-user fa-lg fa-fw" aria-hidden="true"></i>
		</div>

		<div class="field cp_iptxt">
			<%= f.email_field :email, placeholder: "メールアドレス", autofocus: true, autocomplete: "email", class: "email" %>
			<i class="fa fa-envelope fa-lg fa-fw" aria-hidden="true"></i>
		</div>

		<div class="field cp_iptxt">
			<% if @minimum_password_length %>
				<em>(<%= @minimum_password_length %> characters minimum)</em>
			<% end %>
			<%= f.password_field :password, placeholder: "パスワード(6文字以上)", autocomplete: "new-password", class: "password" %>
			<i class="fas fa-unlock-alt fa-lg fa-fw" aria-hidden="true"></i>
		</div>

		<div class="field cp_iptxt">
			<%= f.password_field :password_confirmation, placeholder: "パスワード確認(6文字以上)", autocomplete: "new-password", class: "password_confirm" %>
			<i class="fas fa-unlock-alt fa-lg fa-fw" aria-hidden="true"></i>
		</div>

		<div class="submit_field">
			<%= f.submit "登 録", class: "button button-blue submit-btn" %>
		</div>
	<% end %>
	</div>

</div>
<div id="modal2">
	<i id="modal_close" class="fas fa-times pull-right fa-lg"></i>
	<div class="modal-container">

		<h2 class="text-center">ログイン</h2>

		<div class="text-center">
		<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
			<div class="field cp_iptxt">
				<%= f.email_field :email, placeholder: "メールアドレス", autofocus: true, autocomplete: "email", class: "email" %>
				<i class="fa fa-envelope fa-lg fa-fw" aria-hidden="true"></i>
			</div>

			<div class="field cp_iptxt">
				<%= f.password_field :password, placeholder: "パスワード(6文字以上)", autocomplete: "current-password", class: "password" %>
				<i class="fas fa-unlock-alt fa-lg fa-fw" aria-hidden="true"></i>
			</div>

			<% if devise_mapping.rememberable? %>
				<div class="check-box">
					<div class="check-box-child checkbox01">
						<%= f.check_box :remember_me, class: "checkbox01-input" %>
						<%= f.label :remember_me, class: "checkbox01-parts" %>
					</div>
				</div>
			<% end %>

			<div class="submit_field">
				<%= f.submit "ログイン", class: "button button-blue submit-btn" %>
			</div>

		<% end %>
		</div>
	</div>

<%= javascript_include_tag "modal_window.js" %>