config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'mandalas#top'

	devise_for :users, :controllers => {
	:registrations => 'users/registrations',
	:sessions => 'users/sessions'
	}

	get 'users/:id/graph' => 'users#graph', as: 'user_graph'
	resources :users, only: [:show, :edit, :update, :destroy]

	resources :mandalas

	get 'tasks/:id/done' => 'tasks#done', as: 'task_done'
	resources :tasks, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
			:recoverable, :rememberable, :validatable

	has_many :mandalas, :dependent => :destroy
	has_many :tasks, :dependent => :destroy
	has_many :points, :dependent => :destroy
	accepts_nested_attributes_for :mandalas, allow_destroy: true

	validates :name,		presence: true,
							length: { maximum: 10 }
	validates :email,		presence: true,
							length: { maximum: 20 }
	validates :email,		presence: true,
							length: { maximum: 20 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
        clean_up_passwords resource
        flash[:message] = resource.errors.full_messages
        redirect_to root_path(regist: false)
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end




  # private
  # create elseの返り値を上書きするメソッド
  # def response_to_sign_up_failure(resource)
  #   if resource.email == "" && resource.password == nil
  #     redirect_to root_path, alert: "Please fill in the form"
  #   elsif User.pluck(:email).include? resource.email
  #     redirect_to root_path, alert: "email already exists"
  #   end
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :mandala_complete?, only:[:show, :graph ]

  #GET /users/:id (user_path)
  def show
    if @mandala = Mandala.find_by(user_id: current_user.id, achieved: false) #マンダラチャート作成済みかチェック
      @task_new = Task.new
      @tasks = Task.where(user_id: current_user.id, done: false)
      gon.step = 3 #jQuery分岐用
      if params[:overlooking]
        gon.step = "element_overlooking"
        @squares_overlooking = true
        @mandala_center = @mandala
      else
        if params[:element_select]
          gon.step = "element_select"
          @element_select = true
          @around_text = "必要な行動"
          @center_text = "必要な要素"
          @mandala_center = Element.find_by(Mandala_id: @mandala.id, number: params[:element_select])
          text_element #viewに反映させるテキスト情報
        else
          @around_text = "必要な要素"
          @center_text = "達成したい目標"
          @mandala_center = Mandala.find_by(user_id: current_user.id, achieved: false)
          text_mandala #viewに反映させるテキスト情報
        end
      end
    end
    if params[:ajax]
      render partial: 'users/mypage_mandalachart', locals: { center_text: @center_text, around_text: @around_text, element1: @element1,
                                                              element2: @element2,element3: @element3, element4: @element4,
                                                              element5: @element5, element6: @element6, element7: @element7,
                                                              element8: @element8, element9: @element9, element_select: @element_select }, layout: false
    end
  end

  #GET /users/:id/graph (user_graph_path)
  def graph
    @mandala = Mandala.find_by(user_id: current_user.id, achieved: false)
    gon.element = @mandala.elements.pluck(:target) #グラフのラベル用
    if params[:total] #総計表示
      gon.score_all = score_comp(@mandala)
      gon.achieved_comp = achieved_comp(@mandala) #月ごとのタスク実行数
    else
      @weekly = true
      gon.scores_this_week = score_this_week(@mandala) #今週のデータ
      gon.scores_last_week = score_last_week(@mandala) #先週のデータ
      gon.task_comp_this_week = achieved_this_week(@mandala) #今週のデータ
      gon.task_comp_last_week = achieved_last_week(@mandala) #先週のデータ
    end
  end

  #GET /users/:id/edit (edit_user_path)
  def edit
    @user = current_user
  end

  #PACTH /users/:id (user_path)
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end





  private

#-------------------- graph計算メソッド --------------------#

  def score_this_week(mandala)
    elements = mandala.elements.pluck(:id) # idを配列形式に
    scores = {} #ハッシュ形式で保存する宣言
    elements.each { |element| scores[element] = 0 } # { id => 0, id => 0,...}のハッシュ形式に
    points = Point.where(element_id: elements)
    this_week = points.on_this_week
    this_week.each{ |key,value| scores[key] = value}

    return scores.values
  end

  def score_last_week(mandala)
    elements = mandala.elements.pluck(:id) # idを配列形式に
    scores = {} #ハッシュ形式で保存する宣言
    elements.each { |element| scores[element] = 0 } # { id => 0, id => 0,...}のハッシュ形式に
    points = Point.where(element_id: elements)
    last_week = points.on_last_week
    last_week.each{ |key,value| scores[key] = value}

    return scores.values
  end

  def achieved_this_week(mandala)
    by_weekday = {0 => 0, 1 => 0, 2 => 0, 3 => 0, 4 => 0, 5 => 0, 6 => 0} #曜日別タスク完了数を初期化
    elements = mandala.elements.pluck(:id)
    points = Point.where(element_id: elements)
    this_week = points.this_week
    by_date = this_week.group_by{|w| w.created_at.wday }
    by_date.each{ |key, value| by_weekday[key] = value.count }

    return by_weekday.values
  end

  def achieved_last_week(mandala)
    by_weekday = {0 => 0, 1 => 0, 2 => 0, 3 => 0, 4 => 0, 5 => 0, 6 => 0} #曜日別タスク完了数を初期化
    elements = mandala.elements.pluck(:id)
    points = Point.where(element_id: elements)
    points_last_week = points.last_week
    by_date = points_last_week.group_by{|u| u.created_at.wday }
    by_date.each{ |key, value| by_weekday[key] = value.count }

    return by_weekday.values
  end

  def score_comp(mandala)
    elements = mandala.elements.pluck(:id) # idを配列形式に
    points = Point.where(element_id: elements)
    scores = {} #ハッシュ形式で保存する宣言
    elements.each { |element| scores[element] = 0 } # { id => 0, id => 0,...}のハッシュ形式に
    points_comp = points.element_points
    points_comp.each{ |key,value| scores[key] = value}

    return scores.values
  end

  def achieved_comp(mandala)
    elements = mandala.elements.pluck(:id) # idを配列形式に
    points = Point.where(element_id: elements)
    hash = {}
    6.times.map do |i|
      hash.store((Date.today - i.months).mon, points.where.not(created_at: (Date.today - i.months).next_month.beginning_of_month..Float::INFINITY ))
    end
    result = hash.map do |key,value|
      value.count
    end
    return result.sort!
  end



#-------------------- viewに反映するテキスト処理 --------------------#

  def text_mandala
    @element1 = Element.find_by(mandala_id: @mandala_center.id, number: 1)
    @element2 = Element.find_by(mandala_id: @mandala_center.id, number: 2)
    @element3 = Element.find_by(mandala_id: @mandala_center.id, number: 3)
    @element4 = Element.find_by(mandala_id: @mandala_center.id, number: 4)
    @element5 = @mandala_center
    @element6 = Element.find_by(mandala_id: @mandala_center.id, number: 5)
    @element7 = Element.find_by(mandala_id: @mandala_center.id, number: 6)
    @element8 = Element.find_by(mandala_id: @mandala_center.id, number: 7)
    @element9 = Element.find_by(mandala_id: @mandala_center.id, number: 8)
  end

  def text_element
    @element5 = @mandala_center
    if @mandala_center.activities.present?
      @element1 = Activity.find_by(element_id: @mandala_center.id, number: 1)
      @element2 = Activity.find_by(element_id: @mandala_center.id, number: 2)
      @element3 = Activity.find_by(element_id: @mandala_center.id, number: 3)
      @element4 = Activity.find_by(element_id: @mandala_center.id, number: 4)
      @element6 = Activity.find_by(element_id: @mandala_center.id, number: 5)
      @element7 = Activity.find_by(element_id: @mandala_center.id, number: 6)
      @element8 = Activity.find_by(element_id: @mandala_center.id, number: 7)
      @element9 = Activity.find_by(element_id: @mandala_center.id, number: 8)
    end
  end

#-------------------- 以下ストロングパラメータの記述 --------------------#

  def sign_in_auth
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mandala_mypage.html.erb
<div class="row text-center">
	<div class="mp_ol_squares squares-gray">
		<div id="element1" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 1).target %></p>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element2" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 2).target %></p>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element3" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 3).target %></p>
		</div>
	</div>
</div>
<div class="row text-center">
	<div class="mp_ol_squares squares-gray">
		<div id="element4" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 4).target %></p>
		</div>
	</div>
	<div class="mp_ol_squares squares-white">
		<div id="element5" class="box modal-open" target="#input-modal">
			<p class="text"><%= element.target %></p>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element6" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 5).target %></p>
		</div>
	</div>
</div>
<div class="row text-center">
	<div class="mp_ol_squares squares-gray">
		<div id="element7" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 6).target %></p>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element8" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 7).target %></p>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element9" class="box modal-open" target="#input-modal">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 8).target %></p>
		</div>
	</div>
</div>

app/views/users/_mandala_overlooking.html.erb
<div class="row">
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 1) %>
	</div>
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 2) %>
	</div>
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 3) %>
	</div>
</div>
<div class="row">
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 4) %>
	</div>
	<div class="col-md-4 mp_element">
		<div class="row text-center">
			<div class="mp_ol_squares squares-gray">
				<div id="element1" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 1).target %></p>
				</div>
			</div>
			<div class="mp_ol_squares squares-gray">
				<div id="element2" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 2).target %></p>
				</div>
			</div>
			<div class="mp_ol_squares squares-gray">
				<div id="element3" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 3).target %></p>
				</div>
			</div>
		</div>
		<div class="row text-center">
			<div class="mp_ol_squares squares-gray">
				<div id="element4" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 4).target %></p>
				</div>
			</div>
			<div class="mp_ol_squares squares-white">
				<div id="element5" class="box">
					<p class="text"><%= @mandala_center.target %></p>
				</div>
			</div>
			<div class="mp_ol_squares squares-gray">
				<div id="element6" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 5).target %></p>
				</div>
			</div>
		</div>
		<div class="row text-center">
			<div class="mp_ol_squares squares-gray">
				<div id="element7" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 6).target %></p>
				</div>
			</div>
			<div class="mp_ol_squares squares-gray">
				<div id="element8" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 7).target %></p>
				</div>
			</div>
			<div class="mp_ol_squares squares-gray">
				<div id="element9" class="box">
					<p class="text"><%= Element.find_by(mandala_id: mandala_center.id, number: 8).target %></p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 5) %>
	</div>
</div>
<div class="row">
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 6) %>
	</div>
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 7) %>
	</div>
	<div class="col-md-4 mp_element">
		<%= render 'users/mandala_overlooking_element', element: Element.find_by(mandala_id: mandala_center.id, number: 8) %>
	</div>
</div>

app/views/users/_mandala_overlooking_element.html.erb
<div class="row text-center">
	<div class="mp_ol_squares squares-gray">
		<div id="element1" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 1).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element2" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 2).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element3" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 3).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
</div>
<div class="row text-center">
	<div class="mp_ol_squares squares-gray">
		<div id="element4" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 4).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
	<div class="mp_ol_squares squares-white">
		<div id="element_center" class="box">
			<p class="text"><%= element.target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element5" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 5).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
</div>
<div class="row text-center">
	<div class="mp_ol_squares squares-gray">
		<div id="element6" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 6).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element7" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 7).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
	<div class="mp_ol_squares squares-gray">
		<div id="element8" class="box task_select">
			<p class="text"><%= Activity.find_by(element_id: element.id, number: 8).target %></p>
			<%= hidden_field_tag :element_id, element.id %>
			<%= hidden_field_tag :user_id, current_user.id %>
		</div>
	</div>
</div>

app/views/users/_todo_content.html.erb
<div id="message_area">
	<% if flash[:errors] %>
		<div class="alert alert-warning" role="alert" id="divAlert">
			<i id="alert_close" class="fas fa-times pull-right fa-lg"></i>
			<p>エラー<%= flash[:errors].count %>件発生</p>
			<% flash[:errors].each do |message| %>
				<p>・<%= message %>!</p>
			<% end %>
		</div>
	<% end %>
</div>

<div class="table-responsive">
	<table class="table table-hover" id="todoList">
		<thead>
			<tr>
				<th width="10%"></th>
				<th class="text-center" width="50%">タスク内容</th>
				<th class="text-center" width="30%">期限</th>
				<th width="10%"></th>
			</tr>
		</thead>
		<tbody>
			<% unless tasks.blank? %>
				<% tasks.each do |task| %>
				<tr class="task_content">
					<%= hidden_field_tag :task_id, task.id, id: "task_id" %>
					<td><%= link_to "完了", task_done_path(task.id), id: "btnDone", class: "btn btn-primary btnDone", remote: true %></td>
					<td class="text-center"><%= task.content %></td>
					<td class="text-center"><%= task.limit %></td>
					<td>
						<%= link_to task_path(task.id), method: :delete, id: "btnDel", class: "btn btn-danger btnDel", remote: true do %>
							<i class="fas fa-trash-alt"></i>
						<% end %>
					</td>
				</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="container-main">
	<header class="text-center sub_header">
		<h2>マイページ</h2>
		<% if @mandala %>
			<h1><%= @mandala.target %></h1>
		<% end %>
	</header>
	<% if @mandala %> <!-- マンダラチャート作成済み時の表示 -->
		<div class="col-md-6">
			<h3 class="bg-light">マンダラチャート</h3>
			<div id="mandala_field">
				<% if @squares_overlooking == true %>
					<!-- マンダラチャートを俯瞰図で表示 -->
					<%= render '/users/mandala_overlooking', mandala_center: @mandala %>
				<% else %>
					<!-- マンダラチャートを 9マスで表示 -->
					<%= render '/users/mypage_mandalachart', center_text: @center_text, around_text: @around_text, element1: @element1, element2: @element2,
					element3: @element3, element4: @element4, element5: @element5, element6: @element6, element7: @element7,
					element8: @element8, element9: @element9, element_select: @element_select %>
				<% end %>
			</div>
			<div class="row text-center margin-top margin-bottom">
				<%= link_to "編集する", edit_mandala_path(@mandala_center.id), class: "button button-min button-blue margin-right-min" %>
				<% if @squares_overlooking == true %>
					<%= link_to "3×3表示に戻す", user_path(current_user.id), class: "button button-min button-blue" %>
				<% else %>
					<%= link_to "俯瞰図で見る", user_path(current_user.id, overlooking: true), class: "button button-min button-blue" %>
				<% end %>
			</div>
		</div>
		<div class="col-md-6">
			<h3 class="bg-light">TODOリスト</h3>
			<%= form_for @task_new, remote: true do |f| %>
			<%= f.hidden_field :user_id, :value => current_user.id %>
				<div class="form-row">
					<div class="form-group  col-sm-3">
						<%= f.label '要素' %>
						<div class="select_box">
							<%= f.collection_select :element_id, @mandala.elements, :id, :target %>
						</div>
					</div>
					<div class="form-group col-sm-6">
						<%= f.label 'タスク' %>
						<%= f.text_field :content, id: "inputTask", class: "form-control", :placeholder => "20文字以内で入力してください", :maxlength => "30" %>
					</div>
					<div class="form-group col-sm-3">
						<%= f.label '期限' %>
						<%= f.date_field :limit, id: "inputLimit", class: "form-control", value: "", :placeholder => "" %>
					</div>
				</div>
				<input type="button" id="btnAdd_chart" class="btn btn-primary " value="マンダラチャートから追加">
				<%= f.submit "追加", id: "btnAdd", class: "btn btn-primary text-right pull-right" %>
			<% end %>
			<div class="todo_area">
				<div id="add_task_messages" class="alert alert-info">
					<i id="message_close" class="fas fa-times pull-right fa-lg"></i>
					<p>チャートから「必要な行動」を選択することで、タスクに登録することが出来ます!</p>
				</div>
				<div id="todo_content">
					<%= render'users/todo_content', tasks: @tasks %>
				</div>
			</div>
		</div>
	<% else %> <!-- マンダラチャート作成していない時の表示 -->
		<div class="mandala_not_created text-center">
			<p>
				まだマンダラチャートが作成されていません。<br>
				マンダラチャートを作成することで、すべての機能が使用できるようになります！
			</p>
			<%= link_to "新規作成する", new_mandala_path, class: "button button-blue" %>
		</div>
	<% end %>
</div>



<%= javascript_include_tag "mandalas_new.js" %>
<%= javascript_include_tag "todo_list.js" %>