config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'mandalas#top'

	devise_for :users, :controllers => {
	:registrations => 'users/registrations',
	:sessions => 'users/sessions'
	}

	get 'users/:id/graph' => 'users#graph', as: 'user_graph'
	resources :users, only: [:show, :edit, :update, :destroy]

	resources :mandalas

	get 'tasks/:id/done' => 'tasks#done', as: 'task_done'
	resources :tasks, only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manda-la</title>
    <%= include_gon(init: true) %> <!-- gon gem読み込み -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <%= stylesheet_link_tag    'normalize' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://github.com/nagix/chartjs-plugin-colorschemes/releases/download/v0.2.0/chartjs-plugin-colorschemes.min.js"></script>
  </head>

  <body>

    <div>
      <ul id="gn-menu" class="gn-menu-main">
        <li>
          <%= link_to root_path, class: "no-hover" do %>
            <img src="/images/logo.png">
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "gn-icon gn-icon-logout" do %>
              <span>ログアウト</span>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user.id), class: "gn-icon gn-icon-mypage" do %>
              <span>マイページ</span>
            <% end %>
            <ul class="gn-menu-sub">
              <li>
                <%= link_to edit_user_path(current_user.id), class: "gn-icon gn-icon-user-edit" do %>
                  <span>ユーザ情報編集</span>
                <% end %>
              </li>
              <% if Mandala.find_by(user_id: current_user.id, achieved: false) %>
                 <li>
                  <%= link_to edit_mandala_path(Mandala.find_by(user_id: current_user.id, achieved: false)), class: "gn-icon gn-icon-squares" do %>
                    <span>チャートを編集</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to user_graph_path(current_user.id), class: "gn-icon gn-icon-graph" do %>
                    <span>タスク達成度</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li><a class="gn-icon gn-icon-login modal_open" target="#modal2"><span>ログイン</span></a></li>
          <li><a class="gn-icon gn-icon-user-regist modal_open" target="#modal1"><span>会員登録</span></a></li>
        <% end %>
      </ul>
    </div>

    <%= yield %>

  </body>
</html>